version: '3'
services:
  node-project:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - ./:/app
      - /app/node_modules
    # environment:
    #   - PORT=3000
    env_file:
      - ./.env
    depends_on:
      - database
  
  database:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=database
      - MONGO_INITDB_ROOT_PASSWORD=duracell
    volumes:
      - mongo-db:/data/db

volumes:
  mongo-db: